!
!  ConsoleApp.f90
!
!  Fortran Console Application 
!  Generated by PGI Visual Fortran(R)
!  18.02.2013 21:32:32


program Main  
   use variables
   use constants
   
   call InitiliseVariables
   call InitFields
   call initObstacle
   call InitPressureA
   
   
   call UVSolver  
   
   call DestroyVariables 
    
end program Main



!-------------------------------------!
! Run solver for velocity             !
!                                     !
!-------------------------------------!
subroutine UVSolver
   use variables
   use constants
   use omp_lib
   real (kind=TypeFloat), dimension(0:Mx) :: A 
   real (kind=TypeFloat), dimension(0:Mx) :: B
   real (kind=TypeFloat), dimension(0:Mx) :: C
   real (kind=TypeFloat), dimension(0:Mx) :: F
   real (kind=TypeFloat), dimension(0:Mx+1) :: X
   integer :: printtime
   real time1,time2,time3,time4
   do iter=1,MaxTime
   time1=omp_get_wtime() 
	!***************  U po x       
     do k=1,MaxO
       !$omp parallel default(shared), private(i,j,A,B,C,F)
       !$omp do schedule(dynamic)       
       do j=1,MaxN
       	 do i=1,MaxM
            if (Obstacle(i,j,k).eq.1) then
                A(i)=0.0
                B(i)=1.0
                C(i)=0.0
                F(i)=0.0
            else
                A(i) = -0.5*(-u(i,j,k)*addx(i,j,k) + ad2dx2(i,j,k)/Re + adtau1dx(i,j,k))
                B(i) = -0.5*(-u(i,j,k)*bddx(i,j,k) + bd2dx2(i,j,k)/Re + bdtau1dx(i,j,k)) + 1.0/dt
                C(i) = -0.5*(-u(i,j,k)*cddx(i,j,k) + cd2dx2(i,j,k)/Re + cdtau1dx(i,j,k))
                F(i) = 0.5*(-u(i,j,k)*dudx(i,j,k,0) + d2udx2(i,j,k,0)/Re) +&
                           (-v(i,j,k)*dudy(i,j,k,0) + d2udy2(i,j,k,0)/Re) +&
                           (-w(i,j,k)*dudz(i,j,k,0) + d2udz2(i,j,k,0)/Re) +u(i,j,k)/dt
            endif
         enddo
         A(0)=aUx1(j,k)
         B(0)=bUx1(j,k)
         C(0)=aUx2(j,k)
         F(0)=bUx2(j,k)       
		 call sweepB(A,B,C,F,X,ByX)
         forall (i=0:MaxM+1)	Uo13(i,j,k)=X(i)  
       enddo
       !$omp end do nowait
       !$omp end parallel 
     enddo
!     call WriteFile(VarU13,Iter)
	!***************  U po y   
     do k=1,MaxO   
       !$omp parallel default(shared), private(i,j,A,B,C,F) 
       !$omp do schedule(dynamic)
	   do i=1,MaxM
		 do j=1,MaxN
            if (Obstacle(i,j,k).eq.1) then
                A(j)=0.0
                B(j)=1.0
                C(j)=0.0
                F(j)=0.0
            else
                A(j) = -0.5*(-v(i,j,k)*addy(i,j,k) + ad2dy2(i,j,k)/Re + adtau1dy(i,j,k))
                B(j) = -0.5*(-v(i,j,k)*bddy(i,j,k) + bd2dy2(i,j,k)/Re + bdtau1dy(i,j,k)) + 1.0/dt
                C(j) = -0.5*(-v(i,j,k)*cddy(i,j,k) + cd2dy2(i,j,k)/Re + cdtau1dy(i,j,k))
                F(j) = -0.5*(-v(i,j,k)*dudy(i,j,k,0) + d2udy2(i,j,k,0)/Re) + Uo13(i,j,k)/dt & 
                       +vt(12,jplus12,i,j,k)*(v(i+1,j+1,k)-v(i+1,j,k))/(dx*dy)&
                       -vt(12,jminus12,i,j,k)*(v(i,j+1,k)-v(i,j,k))/(dx*dy)  
            endif
         enddo
         A(0)=aUy1(i,k)
         B(0)=bUy1(i,k)
         C(0)=aUy2(i,k)
         F(0)=bUy2(i,k)
    	 call sweepB(A,B,C,F,X,ByY)
         forall (j=0:MaxN+1) Uo23(i,j,k)=X(j)
       enddo
       !$omp end do nowait
       !$omp end parallel        
     enddo
!     call WriteFile(VarU23,Iter)     
	!***************  U po z
     do i=1,MaxM  
       !$omp parallel default(shared), private(j,k,A,B,C,F)
       !$omp do schedule(dynamic)
	   do j=1,MaxN
		 do k=1,MaxO
            if (Obstacle(i,j,k).eq.1) then
                A(k)=0.0
                B(k)=1.0
                C(k)=0.0
                F(k)=0.0
            else
                A(k) = -0.5*(-w(i,j,k)*addz(i,j,k) + ad2dz2(i,j,k)/Re + adtau1dz(i,j,k))
                B(k) = -0.5*(-w(i,j,k)*bddz(i,j,k) + bd2dz2(i,j,k)/Re + bdtau1dz(i,j,k)) + 1.0/dt
                C(k) = -0.5*(-w(i,j,k)*cddz(i,j,k) + cd2dz2(i,j,k)/Re + cdtau1dz(i,j,k))
                F(k) = -0.5*(-w(i,j,k)*dudz(i,j,k,0) + d2udz2(i,j,k,0)/Re) + Uo23(i,j,k)/dt &
                       +vt(13,kplus12,i,j,k)*(w(i+1,j,k+1)-w(i,j,k+1))/(dx*dz)&
                       -vt(13,kminus12,i,j,k)*(w(i+1,j,k)-w(i,j,k))/(dx*dz)       
            endif
         enddo
         A(0)=aUz1(i,j)
         B(0)=bUz1(i,j)
         C(0)=aUz2(i,j)
         F(0)=bUz2(i,j)
    	 call sweepB(A,B,C,F,X,ByZ)
         forall (k=0:MaxO+1) Uon(i,j,k)=X(k)
       enddo
       !$omp end do nowait
       !$omp end parallel        
     enddo
     time2=omp_get_wtime() 
   !***************  V po x 
     do k=1,MaxO  
       !$omp parallel default(shared), private(i,j,A,B,C,F)
       !$omp do schedule(dynamic)    
	   do j=1,MaxN
		 do i=1,MaxM
            if (Obstacle(i,j,k).eq.1) then
                A(i)=0.0
                B(i)=1.0
                C(i)=0.0
                F(i)=0.0
            else 
                A(i) = -0.5*(-u(i,j,k)*addx(i,j,k) + ad2dx2(i,j,k)/Re + adtau2dx(i,j,k))
                B(i) = -0.5*(-u(i,j,k)*bddx(i,j,k) + bd2dx2(i,j,k)/Re + bdtau2dx(i,j,k)) + 1.0/dt
                C(i) = -0.5*(-u(i,j,k)*cddx(i,j,k) + cd2dx2(i,j,k)/Re + cdtau2dx(i,j,k))
                F(i) = 0.5*(-u(i,j,k)*dvdx(i,j,k,0) + d2vdx2(i,j,k,0)/Re) +&
                           (-v(i,j,k)*dvdy(i,j,k,0) + d2vdy2(i,j,k,0)/Re) +&
                           (-w(i,j,k)*dvdz(i,j,k,0) + d2vdz2(i,j,k,0)/Re) +v(i,j,k)/dt&
                       +vt(21,iplus12,i,j,k)*(u(i+1,j+1,k)-u(i+1,j,k))/(dx*dy)&
                       -vt(21,iminus12,i,j,k)*(u(i,j+1,k)-u(i,j,k))/(dx*dy)       
            endif
         enddo
         A(0)=aVx1(j,k)
         B(0)=bVx1(j,k)
         C(0)=aVx2(j,k)
         F(0)=bVx2(j,k)
		 call sweepB(A,B,C,F,X,ByX)
         forall (i=0:MaxM+1)	Vo13(i,j,k)=X(i)  
       enddo
       !$omp end do nowait
       !$omp end parallel              
     enddo
!    call WriteFile(VarV13,Iter)           
	!**************  V po y
     do k=1,MaxO  
       !$omp parallel default(shared), private(i,j,A,B,C,F) 
       !$omp do schedule(dynamic)    
	   do i=1,MaxM
		 do j=1,MaxN
             if (Obstacle(i,j,k).eq.1) then
                A(j)=0.0
                B(j)=1.0
                C(j)=0.0
                F(j)=0.0
            else
                A(j) = -0.5*(-v(i,j,k)*addy(i,j,k) + ad2dy2(i,j,k)/Re + adtau2dy(i,j,k))
                B(j) = -0.5*(-v(i,j,k)*bddy(i,j,k) + bd2dy2(i,j,k)/Re + bdtau2dy(i,j,k)) + 1.0/dt
                C(j) = -0.5*(-v(i,j,k)*cddy(i,j,k) + cd2dy2(i,j,k)/Re + cdtau2dy(i,j,k))
                F(j) = -0.5*(-v(i,j,k)*dvdy(i,j,k,0) + d2vdy2(i,j,k,0)/Re) + Vo13(i,j,k)/dt
            endif
         enddo
         A(0)=aVy1(i,k)
         B(0)=bVy1(i,k)
         C(0)=aVy2(i,k)
         F(0)=bVy2(i,k)
		 call sweepB(A,B,C,F,X,ByY)
         forall (j=0:MaxN+1) Vo23(i,j,k)=X(j)
       enddo
       !$omp end do nowait
       !$omp end parallel        
     enddo
!    call WriteFile(VarV23,Iter)                
    !***************  V po z
     do i=1,MaxM 
       !$omp parallel default(shared), private(j,k,A,B,C,F)
       !$omp do schedule(dynamic) 
	   do j=1,MaxN
		 do k=1,MaxO
            if (Obstacle(i,j,k).eq.1) then
                A(k)=0.0
                B(k)=1.0
                C(k)=0.0
                F(k)=0.0
            else
                A(k) = -0.5*(-w(i,j,k)*addz(i,j,k) + ad2dz2(i,j,k)/Re + adtau2dz(i,j,k))
                B(k) = -0.5*(-w(i,j,k)*bddz(i,j,k) + bd2dz2(i,j,k)/Re + bdtau2dz(i,j,k)) + 1.0/dt
                C(k) = -0.5*(-w(i,j,k)*cddz(i,j,k) + cd2dz2(i,j,k)/Re + cdtau2dz(i,j,k))
                F(k) = -0.5*(-w(i,j,k)*dvdz(i,j,k,0) + d2vdz2(i,j,k,0)/Re) + Vo23(i,j,k)/dt&
                       +vt(23,kplus12,i,j,k)*(w(i,j+1,k+1)-w(i,j,k+1))/(dy*dz)&
                       -vt(23,kminus12,i,j,k)*(w(i,j+1,k)-w(i,j,k))/(dy*dz)   
            endif
         enddo
         A(0)=aVz1(i,j)
         B(0)=bVz1(i,j)
         C(0)=aVz2(i,j)
         F(0)=bVz2(i,j)
    	 call sweepB(A,B,C,F,X,ByZ)
         forall (k=0:MaxO+1) Von(i,j,k)=X(k)
       enddo
       !$omp end do nowait
       !$omp end parallel       
     enddo
     
   !***************  W po x 
     do k=1,MaxO 
       !$omp parallel default(shared), private(i,j,A,B,C,F) 
       !$omp do schedule(dynamic) 
	   do j=1,MaxN
		 do i=1,MaxM
            if (Obstacle(i,j,k).eq.1) then
                A(i)=0.0
                B(i)=1.0
                C(i)=0.0
                F(i)=0.0
            else 
                A(i) = -0.5*(-u(i,j,k)*addx(i,j,k) + ad2dx2(i,j,k)/Re + adtau3dx(i,j,k))
                B(i) = -0.5*(-u(i,j,k)*bddx(i,j,k) + bd2dx2(i,j,k)/Re + bdtau3dx(i,j,k)) + 1.0/dt
                C(i) = -0.5*(-u(i,j,k)*cddx(i,j,k) + cd2dx2(i,j,k)/Re + cdtau3dx(i,j,k))
                F(i) = 0.5*(-u(i,j,k)*dwdx(i,j,k,0) + d2wdx2(i,j,k,0)/Re) +&
                           (-v(i,j,k)*dwdy(i,j,k,0) + d2wdy2(i,j,k,0)/Re) +&
                           (-w(i,j,k)*dwdz(i,j,k,0) + d2wdz2(i,j,k,0)/Re) +w(i,j,k)/dt&
                       +vt(31,iplus12,i,j,k)*(u(i+1,j,k+1)-u(i,j,k+1))/(dx*dz)&
                       -vt(31,iminus12,i,j,k)*(u(i+1,j,k)-u(i,j,k))/(dx*dz)   
            endif
            
         enddo
         A(0)=aWx1(j,k)
         B(0)=bWx1(j,k)
         C(0)=aWx2(j,k)
         F(0)=bWx2(j,k)
		 call sweepB(A,B,C,F,X,ByX)
         forall (i=0:MaxM+1)	Wo13(i,j,k)=X(i)  
       enddo
       !$omp end do nowait
       !$omp end parallel       
     enddo
!    call WriteFile(VarW13,Iter)           
    
	!**************  w po y
     do k=1,MaxO
       !$omp parallel default(shared), private(i,j,A,B,C,F)   
       !$omp do schedule(dynamic) 
	   do i=1,MaxM
		 do j=1,MaxN
             if (Obstacle(i,j,k).eq.1) then
                A(j)=0.0
                B(j)=1.0
                C(j)=0.0
                F(j)=0.0
            else
                A(j) = -0.5*(-v(i,j,k)*addy(i,j,k) + ad2dy2(i,j,k)/Re + adtau3dy(i,j,k))
                B(j) = -0.5*(-v(i,j,k)*bddy(i,j,k) + bd2dy2(i,j,k)/Re + bdtau3dy(i,j,k)) + 1.0/dt
                C(j) = -0.5*(-v(i,j,k)*cddy(i,j,k) + cd2dy2(i,j,k)/Re + cdtau3dy(i,j,k))
                F(j) = -0.5*(-v(i,j,k)*dwdy(i,j,k,0) + d2wdy2(i,j,k,0)/Re) + Wo13(i,j,k)/dt&
                       +vt(32,jplus12,i,j,k)*(v(i,j+1,k+1)-v(i,j+1,k))/(dy*dz)&
                       -vt(32,jminus12,i,j,k)*(v(i,j,k+1)-v(i,j,k))/(dy*dz)   
            endif
         enddo
         A(0)=aWy1(i,k)
         B(0)=bWy1(i,k)
         C(0)=aWy2(i,k)
         F(0)=bWy2(i,k)
		 call sweepB(A,B,C,F,X,ByY)
         forall (j=0:MaxN+1) Wo23(i,j,k)=X(j)
       enddo
       !$omp end do nowait
       !$omp end parallel         
     enddo
!    call WriteFile(VarW23,Iter)       
    
    !***************  W po z
     do i=1,MaxM 
      !$omp parallel default(shared), private(j,k,A,B,C,F)
      !$omp do schedule(dynamic) 
	   do j=1,MaxN
		 do k=1,MaxO
            if (Obstacle(i,j,k).eq.1) then
                A(k)=0.0
                B(k)=1.0
                C(k)=0.0
                F(k)=0.0
            else
                A(k) = -0.5*(-w(i,j,k)*addz(i,j,k) + ad2dz2(i,j,k)/Re + adtau3dz)
                B(k) = -0.5*(-w(i,j,k)*bddz(i,j,k) + bd2dz2(i,j,k)/Re + bdtau3dz) + 1.0/dt
                C(k) = -0.5*(-w(i,j,k)*cddz(i,j,k) + cd2dz2(i,j,k)/Re + cdtau3dz)
                F(k) = -0.5*(-w(i,j,k)*dwdz(i,j,k,0) + d2wdz2(i,j,k,0)/Re) + Wo23(i,j,k)/dt
            endif
         enddo
         A(0)=aWz1(i,j)
         B(0)=bWz1(i,j)
         C(0)=aWz2(i,j)
         F(0)=bWz2(i,j)
    	 call sweepB(A,B,C,F,X,ByZ)
         forall (k=0:MaxO+1) Won(i,j,k)=X(k)
       enddo
       !$omp end do nowait
       !$omp end parallel         
     enddo     
!    call WriteFile(VarV1,Iter)                  
!    forall (i=1:MaxN, j=1:MaxN) v(i,j)=Vo23(i,j)
!    forall (i=1:MaxN, j=1:MaxN) u(i,j)=Uo23(i,j)
    time3=omp_get_wtime() 
    call Poisson_3D
    time4=omp_get_wtime()     
    do k=1,MaxO
        do j=1,MaxN
            do i=1,MaxM-1
                if (Obstacle(i,j,k).eq.1) then
                    u(i,j,k)=0.0
                else
                    u(i,j,k)=Uon(i,j,k)-dt*(p(i+1,j,k)-p(i,j,k))/dx            
                endif
                
            enddo
        enddo
        do i=1,MaxM
            do j=1,MaxN-1
                if (Obstacle(i,j,k).eq.1) then
                    v(i,j,k)=0.0
                else
                    v(i,j,k)=Von(i,j,k)-dt*(p(i,j+1,k)-p(i,j,k))/dy
                endif
            enddo
        enddo
    enddo
    do i=1,MaxM
        do j=1,MaxN
            do k=1,MaxO-1
                if (Obstacle(i,j,k).eq.1) then
                    w(i,j,k)=0.0
                else                
                    w(i,j,k)=Won(i,j,k)-dt*(p(i,j,k+1)-p(i,j,k))/dz
                endif
            enddo
        enddo
    enddo           
!    call WriteFile(VarU,Iter)
!    call WriteFile(VarV,Iter)
     write(*,*) 'Iteration -',Iter
     write(*,*) 'Solve UVW -',time3-time1
     write(*,*) 'Solve Poisson -',time4-time3
     write(*,*) '____________________________'
     if (Mod(Iter,PrintEvery).eq.0) then
         write(*,*) '_______________________________________________________________________________'
         WRITE(*,*) 'Writeing Time: ', Iter
         write(*,*) '_______________________________________________________________________________'
         printtime=Iter/PrintEvery
         call TecplotWrite(printtime,ByXoY,50)
!         call WriteVtkBinUVW(printtime)
         call WriteVtkTxtUVW(printtime)
     endif
   enddo
end subroutine UVSolver
!-------------------------------------!
! Thomas method                       !
!-------------------------------------!
subroutine sweepF(A,B,C,F,X,SweepDir) 
   use variables
   use constants
   real (kind=TypeFloat) :: A(0:Mx),B(0:Mx),C(0:Mx),F(0:Mx)
   real (kind=TypeFloat) :: X(1:Mx)
   real (kind=TypeFloat) :: alfa(Mx+1),beta(Mx+1)
   real (kind=TypeFloat) :: temp
   integer :: SweepDir
   integer :: Lx
   
   if (SweepDir.eq.ByX) then
       Lx=MaxM
   elseif(SweepDir.eq.ByY) then
       Lx=MaxN
   elseif(SweepDir.eq.ByZ) then
       Lx=MaxO       
   endif
   alfa(Lx+1)=C(0)
   beta(Lx+1)=F(0)
   do I=Lx,1,-1
      temp =(B(I)+A(I)*alfa(I+1))
      
      alfa(I)=-C(I)/temp
      beta(I)=(F(I)-A(I)*beta(I+1))/temp
   enddo
     X(1)=(alfa(1)*B(0)+beta(1))/(1.0-alfa(1)*A( 0))
   do I=1,Lx-1
      X(I+1)=alfa(I+1)*X(I)+beta(I+1)
   enddo
end subroutine sweepF


subroutine sweepB(A,B,C,F,X,SweepDir) 
   use variables
   use constants
   double precision :: A(0:Mx),B(0:Mx),C(0:Mx),F(0:Mx)
   double precision :: X(0:Mx+1)
   integer :: I,M,Lx
   integer :: SweepDir
   double precision :: alfa(Mx+1),beta(Mx+1)
   if (SweepDir.eq.ByX) then
       Lx=MaxM
   elseif(SweepDir.eq.ByY) then
       Lx=MaxN
   elseif(SweepDir.eq.ByZ) then
       Lx=MaxO
   endif
   alfa(2)=A(0)
   beta(2)=B(0)
   do I=2,Lx
      alfa(I+1)=-A(I)/(B(I)+C(I)*alfa(I) )
      beta(I+1)=(F(I)-C(I)*beta(I))/(B(I)+C(I)*alfa(I))
   enddo
     X(Lx)=(alfa(Lx+1)*F(0)+beta(Lx+1))/(1.0-C(0)*alfa(Lx+1))
   do I=Lx-1,1,-1
      X(I)=alfa(I+1)*X(I+1)+beta(I+1)
   enddo
     X(Lx+1)=C(0)*X(Lx)+F(0)
     X(0)=A(0)*X(1)+B(0)
end subroutine sweepB


